import { onSchedule } from "firebase-functions/v2/scheduler";
import { getFirestore, FieldValue } from "firebase-admin/firestore";

/**
 * Daily Brief routine — 07:00 local (UTC HH:mm match via user settings).
 * Users with flags.dailyBrief get a template brief + in-app notification.
 */
export const dailyBriefRoutineTick = onSchedule(
  { schedule: "every 15 minutes", region: "us-central1" },
  async () => {
    const db = getFirestore();
    const users = await db.collection("users").where("flags.dailyBrief", "==", true).get();
    const now = new Date();
    const hhmm = `${String(now.getUTCHours()).padStart(2, "0")}:${String(now.getUTCMinutes()).padStart(2, "0")}`;
    const dateKey = now.toISOString().slice(0, 10);

    for (const snap of users.docs) {
      const uid = snap.id;
      const settings = (await db.doc(`dayPlanSettings/${uid}`).get()).data() as
        | { briefAt?: string; tz?: string }
        | undefined;
      const target = settings?.briefAt || "07:00";
      if (hhmm !== target) continue;

      const ref = db.doc(`briefs/${uid}_${dateKey}`);
      const existing = await ref.get();
      if (existing.exists && !existing.data()?.stale) continue;

      await ref.set(
        {
          uid,
          date: dateKey,
          tz: settings?.tz || "UTC",
          source: "template",
          headline: {
            parts: [{ text: "Your brief is ready — open Home to review.", kind: "text" }],
          },
          summary: "Generated by the Daily Brief routine. Refresh on Home for live numbers.",
          meetings: [],
          worthNoting: [],
          stats: [
            { key: "planned", label: "Planned today", value: "—", href: "/my-work" },
            { key: "overdue", label: "Overdue", value: "—", href: "/my-work" },
            { key: "focus", label: "Focus score", value: "—", href: "/my-work" },
            { key: "blocked", label: "Blocked projects", value: "—", href: "/projects" },
          ],
          schedule: [],
          audio: null,
          inputsHash: `routine-${dateKey}`,
          generatedAt: FieldValue.serverTimestamp(),
        },
        { merge: true },
      );

      await db.collection("notifications").doc(uid).collection("items").add({
        title: "Your brief is ready",
        kind: "daily_brief",
        createdAt: FieldValue.serverTimestamp(),
        read: false,
      });
    }
  },
);
