import type { Column, TableGroup } from "../types";

/** Property management & bookkeeping — acceptance template (Step 26). */
export const PROPERTY_MGMT_TEMPLATE = {
  id: "property-management",
  name: "Property management & bookkeeping",
  description: "Properties, rent collection, vendor payments, and maintenance.",
  category: "operations",
  cover: "#2547C4",
  tables: [
    {
      key: "properties",
      name: "Properties & Tenants",
      icon: "🏠",
      nounSingular: "property",
      groups: [
        { id: "g-default", name: "Portfolio", color: "#2547C4", order: 0 },
      ] as TableGroup[],
      columns: [
        { id: "name", name: "Property/unit name", type: "text" as const, required: true, width: 220 },
        {
          id: "type",
          name: "Property type",
          type: "status" as const,
          width: 140,
          options: [
            { id: "apartment", label: "Apartment", tone: "info" as const, color: "blue" as const },
            { id: "house", label: "House", tone: "success" as const, color: "green" as const },
            { id: "condo", label: "Condo", tone: "purple" as const, color: "purple" as const },
            { id: "commercial", label: "Commercial", tone: "warning" as const, color: "orange" as const },
          ],
        },
        { id: "address", name: "Address", type: "text" as const, width: 200 },
        { id: "unit", name: "Unit number", type: "text" as const, width: 100 },
        { id: "manager", name: "Property manager", type: "people" as const, width: 140 },
        { id: "tenant", name: "Tenant name", type: "text" as const, width: 140 },
        { id: "tenantEmail", name: "Tenant email", type: "email" as const, width: 160 },
        { id: "tenantPhone", name: "Tenant phone", type: "phone" as const, width: 130 },
        {
          id: "rent",
          name: "Monthly rent",
          type: "number" as const,
          width: 120,
          summary: "sum" as const,
          config: { format: "currency" as const, currency: "USD", decimals: 0 },
        },
        {
          id: "occupancy",
          name: "Occupancy",
          type: "status" as const,
          width: 120,
          summary: "distribution" as const,
          options: [
            { id: "occupied", label: "Occupied", tone: "success" as const, color: "green" as const },
            { id: "vacant", label: "Vacant", tone: "warning" as const, color: "orange" as const },
          ],
        },
        { id: "leaseStart", name: "Lease start", type: "date" as const, width: 120 },
        { id: "leaseEnd", name: "Lease end", type: "date" as const, width: 120 },
        {
          id: "propStatus",
          name: "Property status",
          type: "status" as const,
          width: 120,
          options: [
            { id: "active", label: "Active", tone: "success" as const, color: "green" as const },
            { id: "inactive", label: "Inactive", tone: "neutral" as const, color: "gray" as const },
          ],
        },
        { id: "docs", name: "Documents", type: "files" as const, width: 120 },
        {
          id: "openMaint",
          name: "Open maintenance",
          type: "rollup" as const,
          width: 120,
          config: { viaColumnId: "maintLink", targetColumnId: "status", fn: "countIf", countIfValue: "completed" },
        },
        {
          id: "daysToLeaseEnd",
          name: "Days to lease end",
          type: "formula" as const,
          width: 120,
          config: {
            expression: "DAYS(TODAY(), {Lease end})",
            resultType: "number" as const,
          },
        },
      ] as Column[],
      sampleRecords: [
        {
          name: "Oakwood Apartment 101",
          type: "apartment",
          address: "12 Oak St",
          unit: "101",
          tenant: "Maya Chen",
          rent: 1600,
          occupancy: "occupied",
          leaseStart: "2025-01-01",
          leaseEnd: "2026-12-31",
          propStatus: "active",
        },
        {
          name: "Maple Grove House",
          type: "house",
          address: "44 Maple Ave",
          unit: "—",
          tenant: "Jordan Lee",
          rent: 2200,
          occupancy: "occupied",
          leaseStart: "2024-06-01",
          leaseEnd: "2026-05-31",
          propStatus: "active",
        },
        {
          name: "Riverside Condo 204",
          type: "condo",
          address: "8 River Rd",
          unit: "204",
          tenant: "Sam Ortiz",
          rent: 1450,
          occupancy: "occupied",
          leaseStart: "2025-03-01",
          leaseEnd: "2026-10-15",
          propStatus: "active",
        },
        {
          name: "Pinecrest Apartment 302",
          type: "apartment",
          address: "99 Pinecrest",
          unit: "302",
          tenant: "",
          rent: 0,
          occupancy: "vacant",
          leaseStart: "",
          leaseEnd: "",
          propStatus: "active",
        },
        {
          name: "Lakeside Commercial Suite A",
          type: "commercial",
          address: "1 Lake Blvd",
          unit: "A",
          tenant: "North Retail LLC",
          rent: 2350,
          occupancy: "occupied",
          leaseStart: "2023-01-01",
          leaseEnd: "2027-01-01",
          propStatus: "active",
        },
      ],
      views: [
        { key: "main", name: "Main table", type: "table" },
        {
          key: "occupied",
          name: "Occupied properties",
          type: "table",
          filters: [{ columnId: "occupancy", op: "is", value: "occupied" }],
        },
        {
          key: "lease-exp",
          name: "Lease expirations",
          type: "table",
          filters: [{ columnId: "leaseEnd", op: "within_days", value: 90 }],
          sort: [{ columnId: "leaseEnd", dir: "asc" }],
        },
        { key: "cal-lease", name: "Lease calendar", type: "calendar", dateColumnId: "leaseEnd" },
      ],
    },
    {
      key: "bookkeeping",
      name: "Bookkeeping & Accounting",
      icon: "📒",
      nounSingular: "task",
      groups: [
        { id: "g-current", name: "Current month", color: "#2547C4", order: 0 },
        { id: "g-next", name: "Next month", color: "#3AAE6C", order: 1 },
      ] as TableGroup[],
      columns: [
        { id: "task", name: "Accounting task", type: "text" as const, required: true, width: 220 },
        {
          id: "property",
          name: "Property",
          type: "link" as const,
          width: 180,
          config: { targetTableId: "properties", multi: false, twoWay: true },
        },
        {
          id: "taskType",
          name: "Task type",
          type: "status" as const,
          width: 140,
          options: [
            { id: "rent", label: "Rent collection", tone: "info" as const, color: "blue" as const },
            { id: "vendor", label: "Vendor payment", tone: "warning" as const, color: "orange" as const },
            { id: "invoice", label: "Invoice", tone: "purple" as const, color: "purple" as const },
            { id: "recon", label: "Reconciliation", tone: "neutral" as const, color: "gray" as const },
          ],
        },
        { id: "assignee", name: "Assigned to", type: "people" as const, width: 140 },
        {
          id: "status",
          name: "Status",
          type: "status" as const,
          width: 130,
          options: [
            { id: "not_started", label: "Not started", tone: "neutral" as const, color: "gray" as const },
            { id: "waiting", label: "Waiting", tone: "warning" as const, color: "yellow" as const },
            { id: "in_progress", label: "In progress", tone: "info" as const, color: "blue" as const },
            { id: "complete", label: "Complete", tone: "success" as const, color: "green" as const, done: true },
          ],
        },
        {
          id: "priority",
          name: "Priority",
          type: "status" as const,
          width: 110,
          options: [
            { id: "low", label: "Low", tone: "neutral" as const, color: "gray" as const },
            { id: "medium", label: "Medium", tone: "info" as const, color: "blue" as const },
            { id: "high", label: "High", tone: "warning" as const, color: "orange" as const },
            { id: "urgent", label: "Urgent", tone: "danger" as const, color: "red" as const },
          ],
        },
        { id: "due", name: "Due date", type: "date" as const, width: 120 },
        {
          id: "amount",
          name: "Amount",
          type: "number" as const,
          width: 110,
          summary: "sum" as const,
          config: { format: "currency" as const, currency: "USD" },
        },
        { id: "completedAt", name: "Completion date", type: "date" as const, width: 120 },
        {
          id: "tenantLookup",
          name: "Tenant",
          type: "lookup" as const,
          width: 140,
          config: { viaColumnId: "property", targetColumnId: "tenant" },
        },
        { id: "notes", name: "Notes", type: "longText" as const, width: 200 },
      ] as Column[],
      sampleRecords: [],
      views: [
        { key: "main", name: "Main table", type: "table" },
        {
          key: "pending",
          name: "Pending payments",
          type: "table",
          filters: [
            { columnId: "status", op: "is_not", value: "complete" },
            { columnId: "taskType", op: "has_any", value: ["rent", "vendor"] },
          ],
          sort: [{ columnId: "due", dir: "asc" }],
        },
        { key: "board", name: "Board", type: "board", groupColumnId: "status" },
        { key: "cal", name: "Calendar", type: "calendar", dateColumnId: "due" },
      ],
    },
    {
      key: "maintenance",
      name: "Maintenance requests",
      icon: "🔧",
      nounSingular: "request",
      groups: [{ id: "g-default", name: "Inbox", color: "#F2620F", order: 0 }] as TableGroup[],
      columns: [
        { id: "request", name: "Request", type: "text" as const, required: true, width: 220 },
        {
          id: "property",
          name: "Property",
          type: "link" as const,
          width: 180,
          config: { targetTableId: "properties", multi: false, twoWay: true },
        },
        { id: "reportedBy", name: "Reported by", type: "text" as const, width: 140 },
        {
          id: "category",
          name: "Category",
          type: "status" as const,
          width: 120,
          options: [
            { id: "plumbing", label: "Plumbing", tone: "info" as const, color: "blue" as const },
            { id: "electrical", label: "Electrical", tone: "warning" as const, color: "yellow" as const },
            { id: "hvac", label: "HVAC", tone: "purple" as const, color: "purple" as const },
            { id: "other", label: "Other", tone: "neutral" as const, color: "gray" as const },
          ],
        },
        {
          id: "priority",
          name: "Priority",
          type: "status" as const,
          width: 120,
          options: [
            { id: "low", label: "Low", tone: "neutral" as const, color: "gray" as const },
            { id: "medium", label: "Medium", tone: "info" as const, color: "blue" as const },
            { id: "high", label: "High", tone: "warning" as const, color: "orange" as const },
            { id: "emergency", label: "Emergency", tone: "danger" as const, color: "red" as const },
          ],
        },
        {
          id: "status",
          name: "Status",
          type: "status" as const,
          width: 120,
          options: [
            { id: "new", label: "New", tone: "info" as const, color: "blue" as const },
            { id: "in_progress", label: "In progress", tone: "warning" as const, color: "yellow" as const },
            { id: "completed", label: "Completed", tone: "success" as const, color: "green" as const, done: true },
          ],
        },
        { id: "vendor", name: "Vendor", type: "text" as const, width: 140 },
        {
          id: "cost",
          name: "Cost",
          type: "number" as const,
          width: 100,
          summary: "sum" as const,
          config: { format: "currency" as const, currency: "USD" },
        },
        { id: "completedAt", name: "Completion date", type: "date" as const, width: 120 },
        { id: "photos", name: "Photos", type: "files" as const, width: 120 },
      ] as Column[],
      sampleRecords: [],
      views: [
        { key: "main", name: "Main table", type: "table" },
        { key: "board", name: "Board", type: "board", groupColumnId: "status" },
        {
          key: "intake",
          name: "Intake form",
          type: "form",
          formColumns: ["request", "property", "reportedBy", "category", "priority", "photos"],
        },
      ],
      forms: [
        {
          key: "intake",
          columns: ["request", "property", "reportedBy", "category", "priority", "photos"],
          public: true,
          successMessage: "Thanks — your request was received.",
        },
      ],
    },
  ],
  links: [
    { fromTable: "bookkeeping", column: "property", toTable: "properties", twoWay: true },
    { fromTable: "maintenance", column: "property", toTable: "properties", twoWay: true },
  ],
  automations: [
    {
      sentence: "When Status changes to Completed (Maintenance), set Completion date to today",
      trigger: { type: "record.changed", tableKey: "maintenance", columnId: "status", to: "completed" },
      actions: [{ type: "set", columnId: "completedAt", value: { fn: "today" } }],
    },
    {
      sentence: "When Priority changes to Emergency, notify Property manager and Alejandro",
      trigger: { type: "record.changed", tableKey: "maintenance", columnId: "priority", to: "emergency" },
      actions: [
        { type: "notify", to: [{ fromColumnId: "manager" }, { userId: "alejandro" }], message: { template: "Emergency maintenance on {Request}" } },
      ],
    },
    {
      sentence: "When Status changes to Complete (Bookkeeping), set Completion date to today",
      trigger: { type: "record.changed", tableKey: "bookkeeping", columnId: "status", to: "complete" },
      actions: [{ type: "set", columnId: "completedAt", value: { fn: "today" } }],
    },
    {
      sentence: "Every month on day 1 at 08:00, create rent collection records for occupied properties",
      trigger: { type: "schedule", cron: "0 8 1 * *", tz: "America/Guatemala" },
      actions: [
        {
          type: "forEachRecord",
          tableKey: "properties",
          where: [{ columnId: "occupancy", op: "is", value: "occupied" }],
          actions: [
            {
              type: "createRecord",
              tableKey: "bookkeeping",
              groupId: "g-current",
              values: {
                task: { template: "Rent collection · {Property/unit name}" },
                taskType: "rent",
                amount: { fromColumn: "rent" },
                due: { template: "day5" },
                status: "not_started",
              },
              link: { fromColumnId: "property" },
            },
          ],
        },
      ],
    },
    {
      sentence: "When Lease end is 60 days away, create renewal task and notify manager",
      trigger: { type: "date.reached", tableKey: "properties", columnId: "leaseEnd", offsetDays: -60, at: "08:00" },
      actions: [
        {
          type: "createRecord",
          tableKey: "bookkeeping",
          values: {
            task: { template: "Lease renewal · {Property/unit name}" },
            taskType: "recon",
            priority: "high",
            status: "not_started",
          },
        },
        { type: "notify", to: [{ fromColumnId: "manager" }], message: { template: "Lease ends soon: {Property/unit name}" } },
      ],
    },
    {
      sentence: "When Occupancy changes to Vacant, create turnover inspection",
      trigger: { type: "record.changed", tableKey: "properties", columnId: "occupancy", to: "vacant" },
      actions: [
        {
          type: "createRecord",
          tableKey: "maintenance",
          values: {
            request: { template: "Turnover inspection · {Property/unit name}" },
            priority: "high",
            status: "new",
            category: "other",
          },
        },
      ],
    },
    {
      sentence: "When Intake form is submitted, set Status to New and notify manager",
      trigger: { type: "form.submitted", formKey: "intake" },
      actions: [
        { type: "set", columnId: "status", value: "new" },
        { type: "notify", to: [{ fromColumnId: "manager" }], message: { template: "New maintenance request" } },
      ],
    },
    {
      sentence: "When Bookkeeping Status is Complete and Task type is Invoice, create Billing invoice",
      trigger: { type: "record.changed", tableKey: "bookkeeping", columnId: "status", to: "complete" },
      conditions: [{ columnId: "taskType", op: "is", value: "invoice" }],
      actions: [{ type: "createInvoice", amountFromColumnId: "amount" }],
    },
  ],
  dashboard: {
    name: "Property operations",
    widgets: [
      { type: "number", title: "Rent collected this month", source: "bookkeeping", metric: "sum", columnId: "amount", filters: [{ columnId: "taskType", value: "rent" }, { columnId: "status", value: "complete" }] },
      { type: "number", title: "Occupancy rate", source: "properties", metric: "occupancyRate" },
      { type: "bar", title: "Open maintenance by priority", source: "maintenance", groupBy: "priority" },
      { type: "number", title: "Overdue accounting tasks", source: "bookkeeping", metric: "overdueCount" },
      { type: "list", title: "Lease expirations next 90 days", source: "properties", viewKey: "lease-exp" },
    ],
  },
};

/** Sample rents must sum to $7,600. */
export function propertySampleRentTotal(): number {
  return PROPERTY_MGMT_TEMPLATE.tables[0].sampleRecords.reduce(
    (s, r) => s + Number(r.rent || 0),
    0,
  );
}
